# profiles.yml

dbtearn:
  outputs:
    dev:
      type: snowflake
      account: mc31305.central-india.azure
      user: ACHUTHA
      password: Achutha@98
      role: ACCOUNTADMIN
      database: AIRBNB
      warehouse: COMPUTE_WH
      schema: DEV
  target: dev
prod:
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('DBT_PROFILE_ACCOUNT') }}"
      user: "{{ env_var('DBT_PROFILE_USER') }}"
      role: ACCOUNTADMIN
      password: "{{ env_var('DBT_PROFILE_PASSWORD') }}"
      database: AIRBNB
      warehouse: COMPUTE_WH
      schema: RAW

