name: dbt production run on push branches to main

on:
  push:
    branches: [ main ]

env:
  DBT_PROFILE_TARGET: prod
  DBT_PROFILE_ACCOUNT: ${{ secrets.DBT_PROFILE_ACCOUNT }}
  DBT_PROFILE_USER: ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD: ${{ secrets.DBT_PROFILE_PASSWORD }}
  DBT_PROFILE_ROLE: ${{ secrets.DBT_PROFILE_ROLE }}
  DBT_PROFILE_DATABASE: ${{ secrets.DBT_PROFILE_DATABASE }}
  DBT_PROFILE_SCHEMA: ${{ secrets.DBT_PROFILE_SCHEMA }}
  DBT_PROFILE_WH: ${{ secrets.DBT_PROFILE_WH }}

jobs:
  dbt_run:
    name: dbt refresh and test on push branches to main
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        working-directory: ./

      - name: Prepare DBT profiles directory
        run: |
          mkdir -p ~/.dbt
          cp profiles.yml ~/.dbt/profiles/profiles.yml
        working-directory: ./

      - name: Save the manifest file from previous run
        run: |
          mkdir -p ~/ci_new_state
          cp target/manifest.json ~/ci_new_state/manifest.json
        working-directory: ./

      - name: Install dbt packages
        run: dbt deps
        # optionally use this parameter
        # to set a main directory of dbt project:
        working-directory: ./

      - name: Run the models
        run: dbt run -s "@state:modified" --defer --state  ~/ci_new_state --profiles-dir ./ --profile github_actions --target prod
        working-directory: ./

      - name: Run tests
        run: dbt test -s "@state:modified" --defer --state  ~/ci_new_state --profiles-dir ./ --profile github_actions --target prod
        working-directory: ./

      - name: Upload manifest.json
        uses: actions/upload-artifact@v2
        with:
          name: dbt-manifest
          path: target/manifest.json
