name: Build and Test on Dev

on:
  push:
    branches: [ dev ]

env:
  DBT_PROFILE_TARGET: dev
  DBT_PROFILE_ACCOUNT: ${{ secrets.DBT_PROFILE_ACCOUNT }}
  DBT_PROFILE_USER: ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD: ${{ secrets.DBT_PROFILE_PASSWORD }}
  DBT_PROFILE_ROLE: ${{ secrets.DBT_PROFILE_ROLE }}
  DBT_PROFILE_DATABASE: ${{ secrets.DBT_PROFILE_DATABASE }}
  DBT_PROFILE_SCHEMA: ${{ secrets.DBT_PROFILE_SCHEMA }}
  DBT_PROFILE_WH: ${{ secrets.DBT_PROFILE_WH }}

jobs:
  build_and_test:
    name: Build and Test dbt Project
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        working-directory: ./

      - name: Prepare DBT profiles directory
        run: |
          mkdir -p ~/.dbt
          cp config/profiles.yml ~/.dbt/profiles.yml  # Update this line if profiles.yml is in a subdirectory
        working-directory: ./

      - name: Install dbt packages
        run: dbt deps --profiles-dir ~/.dbt --profile github_actions --target dev
        working-directory: ./

      - name: Run the models
        run: dbt run --profiles-dir ~/.dbt --profile github_actions --target dev
        working-directory: ./

      - name: Run tests
        run: dbt test --profiles-dir ~/.dbt --profile github_actions --target dev
        working-directory: ./
